### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@carsongregory: would it be possible to pull Python 3 compatibility fixups and make new PyPI release, please?

**Comment by RevolutionTech** [comment]
A few requests:

1. I've just recently corrected an issue with our Circle-CI configuration. Circle-CI should pass if you merge master into your branch.
1. Would you be able to split your changes into two Pull Requests? It would be great to have the Django 1.7+ changes separate from the Python 3 compatibility changes.
1. `func_code` -> `__code__` will break users on Python 2.5. Could we change this to `six.get_function_code()` instead?
1. We'd like to support Django versions as low as 1.4.22, which these changes will also break. Could you make a change to check the Django version and use the `caches` dict for 1.7+, but otherwise use `get_cache()`?

Additionally, I'm afraid we cannot update PyPi as the project is owned by Mikhail Korobov:
https://bitbucket.org/kmike/django-cache-utils/overview

It seems that the project has been abandoned from there.

Thanks PetrDlouhy!

**Comment by PetrDlouhy** [comment]
Maybe we could try to contact @kmike to give us permissions for `django-cache-utils` PyPI. If it would not be possible, we would need to choose another name for the project like `django-cache-util`

**Comment by PetrDlouhy** [comment]
@RevolutionTech Hi, thanks for your inspection. I think, that the only way to ensure wide compatibility is to run the tests with all supported Django/Python.

In #8 I reconfigured Circle-CI tests to run in wide range of versions with Tox. Although I didn't figure out way to run it in Python 2.5, because it is not supported by Tox and other tools anymore.

I am closing this PR in favor of #8, please write your comments there.

**Comment by RevolutionTech** [comment]
I've reached out to @kmike, so hopefully we'll be able to update the version on PyPi. :)

**Comment by PetrDlouhy** [comment]
@RevolutionTech any news about releasing the PyPI package?

**Comment by RevolutionTech** [comment]
I sent Mikhail Korobov an email, but unfortunately he has not replied. 😢

**Pull request closed without merging**
