### PR TITLE
install for Python  3 support

### PR DESCRIPTION
**Pull request by tylerecouture**

### CODE REVIEW

**Comment by RevolutionTech** [comment]
Thank you for the PR.

Actually, we should encourage all users to install the latest version. What are your thoughts on changing the original `pip install` line to:
`$ pip install git+https://github.com/infoscout/django-cache-utils.git`

**Comment by tylerecouture** [comment]
Haha, no idea, I'm pretty much a noob =)  Thanks for the great package.

**Comment by RevolutionTech** [comment]
Nah, you're right that the README is confusing as it is currently. What are your thoughts on changing your PR to make the `pip install` line the one I suggested above?

**Comment by PetrDlouhy** [comment]
@RevolutionTech I think, that you should make PyPI package. Relying on the GitHub source is quite uncomfortable and not feeling very safe. PyPI package will also have proper versioning.

You could try to reach Mikhail Korobov to give you access to the original PyPI repository at https://pypi.python.org/pypi/django-cache-utils/0.7.2
If that is not possible, you should make new PyPI repository with different name like `django-cache-util` or `django-cache-utils3` or something.

**Comment by RevolutionTech** [comment]
I've reached out to Mikhail a few times now, but he hasn't responded. We're planning on creating a new PyPi package, but just wanted to clean up the repo a little bit first. Stay tuned!

**Comment by RevolutionTech** [comment]
We have released the package on PyPi as `djcacheutils` and that has been updated in the README, so I will close out this PR. Thanks!

**Pull request closed without merging**
